2021-01-03 17:56:03,577 INFO: Microblog startup [in D:\_Projects\_Python\microblog\app\logger.py:32]
2021-01-03 17:57:04,159 INFO: Microblog startup [in D:\_Projects\_Python\microblog\app\logger.py:32]
2021-01-03 18:36:48,906 INFO: Microblog startup [in D:\_Projects\_Python\microblog\app\logger.py:32]
2021-01-03 18:37:02,457 INFO: Microblog startup [in D:\_Projects\_Python\microblog\app\logger.py:32]
2021-01-03 18:38:04,309 ERROR: Exception on /reset_password/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJyZXNldF9wYXNzd29yZF9mb3IiOjEsImV4cCI6MTYwOTY4ODgyOS45MTg1OTA1fQ.UKqmCUQ5UfQRa5_yuwRjFuprY8nlo-S3Uf7J7EKtODw [GET] [in d:\_projects\_python\microblog\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "d:\_projects\_python\microblog\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\_projects\_python\microblog\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\_projects\_python\microblog\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\_projects\_python\microblog\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "d:\_projects\_python\microblog\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\_projects\_python\microblog\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\_Projects\_Python\microblog\app\routes.py", line 164, in reset_password
    return render_template('pages/reset_password.html', form=form)
  File "d:\_projects\_python\microblog\venv\lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "d:\_projects\_python\microblog\venv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "d:\_projects\_python\microblog\venv\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "d:\_projects\_python\microblog\venv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "d:\_projects\_python\microblog\venv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "D:\_Projects\_Python\microblog\app\templates\pages\reset_password.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "d:\_projects\_python\microblog\venv\lib\site-packages\flask\templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "d:\_projects\_python\microblog\venv\lib\site-packages\flask\templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: base.html
2021-01-03 18:38:51,015 ERROR: Exception on /reset_password/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJyZXNldF9wYXNzd29yZF9mb3IiOjEsImV4cCI6MTYwOTY4ODgyOS45MTg1OTA1fQ.UKqmCUQ5UfQRa5_yuwRjFuprY8nlo-S3Uf7J7EKtODw [GET] [in d:\_projects\_python\microblog\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "d:\_projects\_python\microblog\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\_projects\_python\microblog\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\_projects\_python\microblog\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\_projects\_python\microblog\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "d:\_projects\_python\microblog\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\_projects\_python\microblog\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\_Projects\_Python\microblog\app\routes.py", line 164, in reset_password
    return render_template('pages/reset_password.html', form=form)
  File "d:\_projects\_python\microblog\venv\lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "d:\_projects\_python\microblog\venv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "d:\_projects\_python\microblog\venv\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "d:\_projects\_python\microblog\venv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "d:\_projects\_python\microblog\venv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "D:\_Projects\_Python\microblog\app\templates\pages\reset_password.html", line 1, in top-level template code
    {% extends "layouts/base.html" %}
  File "d:\_projects\_python\microblog\venv\lib\site-packages\flask\templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "d:\_projects\_python\microblog\venv\lib\site-packages\flask\templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: base.html
